# from dataclasses import dataclass

# @dataclass
# class TrainConfig:
#     # --- Paths ---
#     # Directory where setup.py downloaded the files
#     model_dir: str = "./pretrained_models"
    
#     # Path to your metadata CSV (Format: ID|RawText|NormText)
#     csv_path: str = "./MyTTSDataset/metadata.csv"
#     metadata_path: str = "./metadata.json"
    
#     # Directory containing WAV files
#     wav_dir: str = "./MyTTSDataset/wavs"
#     #wav_dir: str = "./FileBasedDataset"
    
#     preprocessed_dir = "./MyTTSDataset/preprocess"
#     #preprocessed_dir = "./FileBasedDataset/preprocess"
    
#     # Output directory for the finetuned model
#     output_dir: str = "./chatterbox_output"
    
#     is_inference = False
#     inference_prompt_path: str = "./speaker_reference/2.wav"
#     inference_test_text: str = "Merhaba, sesimi geliştirmem oldukça uzun zaman aldı ve şimdi sahip olduğuma göre, sessiz kalmayacağım."


#     ljspeech = True # Set True if the dataset format is ljspeech, and False if it's file-based.
#     json_format = False # Set True if the dataset format is json, and False if it's file-based or ljspeech.
#     preprocess = True # If you've already done preprocessing once, set it to false.
    
#     is_turbo: bool = False # Set True if you're training Turbo, False if you're training Normal.

#     # --- Vocabulary ---
#     # The size of the NEW vocabulary (from tokenizer.json)
#     # Ensure this matches the JSON file generated by your tokenizer script.
#     # For Turbo mode: Use the exact number provided by setup.py (e.g., 52260)
#     new_vocab_size: int = 52260 if is_turbo else 2454 

#     # --- Hyperparameters ---
#     batch_size: int = 16         # Adjust based on VRAM (2, 4, 8)
#     grad_accum: int = 2        # Effective Batch Size = Batch * Accum
#     learning_rate: float = 1e-5 # T3 is sensitive, keep low
#     num_epochs: int = 120
    
#     save_steps: int = 500
#     save_total_limit: int = 5
#     dataloader_num_workers: int = 8

#     # --- Constraints ---
#     start_text_token = 255
#     stop_text_token = 0
#     max_text_len: int = 256
#     max_speech_len: int = 850   # Truncates very long audio
#     prompt_duration: float = 3.0 # Duration for the reference prompt (seconds)



from dataclasses import dataclass

@dataclass
class TrainConfig:
    # ✅ ALL PATHS ON GOOGLE DRIVE
    
    # --- Base Directories (Google Drive) ---
    base_dir: str = "/content/drive/MyDrive/urdu_tts_training/repos/chatterbox-finetuning"
    
    # --- Paths ---
    # Directory where setup.py downloaded the files (ON GOOGLE DRIVE)
    model_dir: str = "./pretrained_models"
    
    # Path to your metadata CSV (Format: ID|RawText|NormText)
    csv_path: str = "./MyTTSDataset/metadata.csv"
    metadata_path: str = "./metadata.json"
    
    # Directory containing WAV files (ON GOOGLE DRIVE)
    wav_dir: str = "./MyTTSDataset/wavs"
    
    # Preprocessed directory (ON GOOGLE DRIVE)
    preprocessed_dir: str = "./MyTTSDataset/preprocess"
    
    # ✅ Output directory for the finetuned model (ON GOOGLE DRIVE)
    # This is where your trained model will be saved
    output_dir: str = "./chatterbox_output"
    
    # ✅ Logs directory (ON GOOGLE DRIVE)
    logs_dir: str = "/content/drive/MyDrive/urdu_tts_training/outputs/logs"
    
    # ✅ Checkpoints directory (ON GOOGLE DRIVE)
    checkpoints_dir: str = "/content/drive/MyDrive/urdu_tts_training/outputs/checkpoints"
    
    # --- Inference Settings ---
    is_inference: bool = False
    inference_prompt_path: str = "./speaker_reference/2.wav"
    inference_test_text: str = "پاکستان ایک خوبصورت ملک ہے۔ یہ اردو ٹیکسٹ ٹو اسپیچ کا ٹیسٹ ہے۔"
    
    # --- Dataset Format ---
    ljspeech: bool = True  # Set True if dataset format is ljspeech
    json_format: bool = False  # Set True if dataset format is json
    preprocess: bool = False  # ✅ Set to False since we already preprocessed
    
    # --- Model Type ---
    is_turbo: bool = False  # ✅ Set True for Turbo, False for Normal
    
    # --- Vocabulary ---
    # ✅ Updated for Urdu dataset
    # The size of the NEW vocabulary (from tokenizer.json)
    new_vocab_size: int = 52260 if is_turbo else 2454
    
    # --- Hyperparameters (Optimized for better results) ---
    batch_size: int = 8  # ✅ Reduced for stability (was 16)
    grad_accum: int = 4  # ✅ Increased to maintain effective batch size of 32
    learning_rate: float = 1e-4  # ✅ Slightly higher for faster convergence (was 1e-5)
    num_epochs: int = 15  # ✅ Reduced for faster iteration (was 120)
    
    # --- Checkpoint Settings ---
    save_steps: int = 200  # ✅ Save more frequently (was 500)
    save_total_limit: int = 5  # Keep last 5 checkpoints
    dataloader_num_workers: int = 4  # ✅ Reduced for stability (was 8)
    
    # --- Constraints ---
    start_text_token: int = 255
    stop_text_token: int = 0
    max_text_len: int = 256
    max_speech_len: int = 850  # Truncates very long audio
    prompt_duration: float = 3.0  # Duration for reference prompt (seconds)
    
    # ✅ Additional Settings for Better Training
    warmup_steps: int = 100  # Gradual learning rate warmup
    weight_decay: float = 0.01  # L2 regularization
    gradient_clip: float = 1.0  # Prevent gradient explosion
    
    # ✅ Logging
    logging_steps: int = 10  # Log every N steps
    eval_steps: int = 200  # Evaluate every N steps